name: build-app-action
on: [push]
jobs:
  build:
    name: CI part
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: composer configuration
        run: |
          composer update
          composer install --no-scripts
      - name: laravel configuration
        run: |
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan migrate
          ./vendor/bin/sail artisan db:seed --class=ProductSeeder
      #- name: running tests
       # run: vendor/bin/phpunit tests/
