name: build-app-action
on: [push]
jobs:
  build:
    name: CI part
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: composer configuration
        run: |
          composer update
          composer install --no-scripts
      - name: laravel configuration
        run: |
          cp /.env .env
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan migrate
          ./vendor/bin/sail artisan db:seed --class=ProductSeeder
      #- name: running tests
       # run: vendor/bin/phpunit tests/
  deploy:
    #needs: build
    name: CD part
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        options: >-
          --name=localstack
          --health-cmd="curl -sS 127.0.0.1:4566 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: |
          curl http://localhost:4566/health
          aws s3 mb s3://bucket-for-images --endpoint-url http://localhost:4566 --region us-east-2
          aws s3 cp .env.example s3://task15 --endpoint-url http://localhost:4566 --region us-east-2
          aws s3 ls s3://bucket-for-images --endpoint-url http://localhost:4566 --region us-east-2
          aws ec2 run-instances --image-id ami-05803413c51f242b7 --instance-type t2.micro --endpoint-url http://localhost:4566 --region us-east-2
          aws ec2 describe-instances --endpoint-url http://localhost:4566 --region us-east-2
        env:
          AWS_ACCESS_KEY_ID: localstack
          AWS_SECRET_ACCESS_KEY: localstack
          AWS_DEFAULT_REGION: "us-east-2"
